obss/sahi

- sahi/predict.py
- scripts/predict_folder.py
> make match_iou_thr configurable

- .gitignore
- sahi/utils/coco.py
> guarantee unique file naming while linking

- conda/meta.yaml
> remove optional dependencies from conda

- sahi/utils/coco.py
> handle duplicate image id

- sahi/annotation.py
fixes https://github.com/obss/sahi/issues/116
> fix scripts/predict.py

- docs/SCRIPTS.md
related with https://github.com/obss/sahi/issues/114#issuecomment-855366208
> add details for coco2yolov5 usage

- requirements.txt
related with https://github.com/obss/sahi/issues/114
> add pyyaml dependency

- .github/workflows/ci.yml
- .github/workflows/package_testing.yml
- docs/MOT.md
- sahi/utils/mot.py
- setup.py
- tests/test_motutils.py
fixes https://github.com/obss/sahi/issues/125
> add mot utils

- sahi/utils/coco.py
related to https://github.com/obss/sahi/issues/114
> handle image files without suffix in yolov5 conversion

- sahi/slicing.py
fixes https://github.com/obss/sahi/issues/140
> add check for image size in `slice_image`

- .github/workflows/ci.yml
- .github/workflows/package_testing.yml
- README.md
- sahi/predict.py
- sahi/utils/fiftyone.py
- scripts/predict_fiftyone.py
fixes https://github.com/obss/sahi/issues/97
> add fiftyone predict script

- sahi/slicing.py
- tests/test_slicing.py
fixes https://github.com/obss/sahi/issues/159
> fix negative bbox coord error

- README.md
fixes https://github.com/obss/sahi/issues/180
> fix mmdet colab url in readme

- sahi/utils/cv.py
fixes https://github.com/obss/sahi/issues/173
> add large tiff image reading support

- sahi/slicing.py
- scripts/slice_coco.py
fixes https://github.com/obss/sahi/issues/175
> add concurrent slice export

- .github/workflows/ci.yml
- requirements.txt
- sahi/scripts/coco_error_analysis.py
- sahi/scripts/coco_evaluation.py
- sahi/utils/fiftyone.py
an attempt to fix: https://github.com/obss/sahi/issues/220
> fix optional dependencies

- docs/COCO.md
- sahi/model.py
- sahi/utils/coco.py
fixes https://github.com/obss/sahi/issues/203
> handle predictions with negative bbox values

- sahi/model.py
- tests/test_mmdetectionmodel.py
- tests/test_predict.py
fixes https://github.com/obss/sahi/issues/265
> fix mmdet channel order

- sahi/annotation.py
- sahi/utils/cv.py
fixes https://github.com/obss/sahi/issues/186 and https://github.com/obss/sahi/issues/235
> handle when mask prediction is empty

- sahi/slicing.py
fixes https://github.com/obss/sahi/issues/241
> handle invalid annotation polygon

- sahi/utils/mmdet.py
handle when
```python
_base_ = '../_base_/default_runtime.py'
```
instead of
```python
_base_ = ['../_base_/default_runtime.py']
```
> improve mmdet config download util

- sahi/postprocess/combine.py
based on https://github.com/obss/sahi/issues/214#issuecomment-979795759
> fix nms postprocess

- README.md
Check `YOLOX` + `SAHI` demo: <a href="https://huggingface.co/spaces/fcakyon/sahi-yolox"><img src="https://raw.githubusercontent.com/obss/sahi/main/resources/hf_spaces_badge.svg" alt="HuggingFace Spaces"></a>
<a href="https://huggingface.co/spaces/fcakyon/sahi-yolox"><img width="600" src="https://user-images.githubusercontent.com/34196005/144092739-c1d9bade-a128-4346-947f-424ce00e5c4f.gif" alt="downloads"></a>
> add demo gif to readme

- sahi/model.py
thanks to @oulcan for reporting.
> fix yolov5 category mapping

- sahi/scripts/coco_error_analysis.py
- sahi/scripts/coco_evaluation.py
fixes https://github.com/obss/sahi/issues/305
> update default params to match coco eval and error analysis

- sahi/scripts/coco_error_analysis.py
fixes https://github.com/obss/sahi/issues/305
> utilize `max_detections` in coco_error_analysis

- sahi/predict.py
fixes https://github.com/obss/sahi/issues/334
> fix visual export for windows

- sahi/postprocess/combine.py
- sahi/postprocess/utils.py
fixes https://github.com/obss/sahi/issues/349
> handle numpy array index in ObjectPredictionList

- README.md
> add kaggle notebook into readme

- sahi/model.py
- sahi/utils/cv.py
fixes https://github.com/obss/sahi/issues/389
> handle invalid mask prediction

- README.md
Oh my ZSH shel kullanan geliştiriciler için ```pip install -e ."[dev]"```  komutunu kullanarak kurulum yapması gerekmektedir.
> Bash ve ZSH paket kurulumu

- .github/workflows/ci.yml
- .github/workflows/package_testing.yml
update to
- yolov5 v6.1.0
- pycocotools v2.0.4
- mmcv v1.4.8
- mmdet 2.23.0
> update package versions in ci

- sahi/predict.py
- deprecate UNIONMERGE postprocess in favor of GREEDYNMM postprocess
- refactor how postprocess instances are created in predict.py
> refactor postprocess call

- sahi/auto_model.py
update `from_layer` metod to be more generic
> refactor automodel

- sahi/model.py
fixes https://github.com/obss/sahi/issues/478
> update device priority for Detectron2DetectionModel

- sahi/predict.py
fixes https://github.com/obss/sahi/issues/480
> fix pickle export for video

- .github/workflows/ci.yml
- .github/workflows/ci_torch1.10.yml
- .github/workflows/package_testing.yml
- docs/mot.md
- sahi/utils/import_utils.py
- sahi/utils/mot.py
- update:
norfair to 1.0.0
mmcv to 1.5.3
mmdet to 2.25.0
yolov5 to 6.1.3
- fix get_package_info in sahi.utils.import_utils.
> update package versions in workflows

- sahi/model.py
- sahi/predict.py
fixes https://github.com/obss/sahi/issues/490
> remove legacy image_size parameter

- sahi/__init__.py
```python
from sahi import AutoDetectionModel
```
> AutoDetectionModel can be imported from sahi

- sahi/annotation.py
- sahi/model.py
- sahi/predict.py
- sahi/scripts/coco_error_analysis.py
- sahi/scripts/coco_evaluation.py
- sahi/scripts/predict.py
- sahi/slicing.py
- sahi/utils/coco.py
- sahi/utils/mot.py
fixed https://github.com/obss/sahi/issues/492
> refactor exception handling

- README.md
add @tureckova, @youngjae-avikus, @mcvarer
> add new contributors to the readme

- sahi/scripts/coco2fiftyone.py
fixes https://github.com/obss/sahi/issues/539
> fix coco2fiftyone script

- sahi/predict.py
fixes https://github.com/obss/sahi/issues/526
thanks to @seekingdeep, @wgq18, @anilozfuttu
> fix segmentation fault in same cases

- sahi/auto_model.py
- sahi/model.py
- sahi/postprocess/combine.py
- sahi/predict.py
- sahi/scripts/predict.py
- sahi/utils/import_utils.py
- sahi/utils/mot.py
- sahi/utils/torch.py
fixes https://github.com/obss/sahi/issues/547
> refactor requirement checking

- .github/workflows/ci.yml
- .github/workflows/ci_torch1.10.yml
- README.md
- scripts/run_code_style.py
- scripts/utils.py
- setup.cfg
- setup.py
> Code formatting and checks are moved to a single module.

- sahi/utils/import_utils.py
> fix an incorrect url in comments

- README.md
- sahi/slicing.py
- warning should not be raised when slice parameters are set, it confuses users
> fix auto slice warning

- sahi/slicing.py
fixes https://github.com/obss/sahi/issues/565
see https://stackoverflow.com/questions/68785427/oserror-errno-24-too-many-open-files
> fix a slice_image error

- setup.py
Related issue https://github.com/PyCQA/flake8/issues/1701
> flake8 dependency fix for python3.7.

- sahi/scripts/coco_evaluation.py
fixes https://github.com/obss/sahi/discussions/700
> fix coco segm eval

- sahi/__init__.py
- tests/test_high_level_api.py
- tests/test_highlevelapi.py
```python
from sahi import BoundingBox, Category, Mask, AutoDetectionModel, DetectionModel, ObjectPrediction
```
> make some classes importable from highest level

- sahi/__init__.py
- sahi/utils/torch.py
fixes the bug mentioned in https://github.com/obss/sahi/discussions/754
> fix device selection, increase version

- docs/coco.md
The save_json function has been imported.
> The coco.md file has been updated.

- sahi/utils/file.py
Would you suggest adding the code?
https://github.com/obss/sahi/blob/main/docs/predict.md
```
result.export_visuals(export_dir="demo_data/")
```
> Added indent parameter to save_json parameter.

- sahi/predict.py
Changes printout like `Performing prediction on 8 number of slices.` to `Performing prediction on 8 slices.`
> Improve printout readability

- sahi/postprocess/combine.py
Remove unused list in `greedy_nmm` function.
> remove an unused list in postprocess

- README.md
add @karl-joan, @jacobmarks, @williamlung, @AmoghDhaliwal into contributors list.
> add more contributors to readme

- tests/test_cvutils.py
- tests/test_fileutils.py
- tests/test_postprocessutils.py
- tests/test_prediction.py
- tests/test_torchutils.py
adding in additional unit tests in this PR in case others need it for any code coverage requirements.
> add more unit tests

- sahi/models/mmdet.py
Solve the issue mentioned in https://github.com/obss/sahi/discussions/1064, which leads to error when `{with_mask:False}`
> Update has_mask method for mmdet models (handle an edge case)

- sahi/predict.py
fixing https://github.com/obss/sahi/discussions/1100
> fix a type hint typo in predict func

- .github/workflows/ci.yml
To diagnose the problem in https://github.com/obss/sahi/actions/runs/14827005444/job/41621570686
@Dronakurl you have any idea what might be causing the error?
> improve package ci logging

- docs/cli.md
> Fix typo and scripts URL

- README.md
> add new contributors to readme

- sahi/slicing.py
Improved some type hints and docstrings for several slicing functions
> Improve type hints and docstrings

- sahi/annotation.py
- tests/test_annotation.py
Small change, similar to the BoundingBox, to make the Category immutable.
> Make Category immutable and add tests

- sahi/postprocess/combine.py
Just removing an outdated argument I found misleading
> Update docstring for greedy_nmm

- .github/workflows/mmdet.yml
- pyproject.toml
Because of SSL problems I disabled url section and CI for sahi to fix installation in dev. Because it does prevent development. 
- https://github.com/open-mmlab/mmcv/issues/3302
- https://github.com/open-mmlab/mmengine/issues/1661
- https://github.com/open-mmlab/mmpose/issues/3237
> fix: 🐛 Update version to 0.11.33 to fix sahi installation in dev

- .github/workflows/ci.yml
- sahi/slicing.py
- sahi/utils/cv.py
- tests/test_cv_utils.py
based on discussion https://github.com/obss/sahi/discussions/1228
> refactor: make exif rotation on image read by default and use PIL built-in ImageOps instead

- pyproject.toml
tests are failing, we need a new release with the latest fixes @onuralpszr 
https://github.com/obss/sahi/actions/workflows/ci.yml?query=branch%3Amain+event%3Aschedule
> build: Bump version from 0.11.33 to 0.11.34
