obss/sahi

.github/workflows/ci.yml, .github/workflows/package_testing.yml, README.md, scripts/predict.py
- `predict.py` script usage:
```bash
python scripts/predict.py --source image/file/or/folder --model_path path/to/model --config_path path/to/config
```
will perform sliced inference on default parameters and export the prediction visuals to runs/predict/exp folder.
You can specify sliced inference parameters as:
```bash
python scripts/predict.py --slice_width 256 --slice_height 256 --overlap_height_ratio 0.1 --overlap_width_ratio 0.1 --iou_thresh 0.25 --source image/file/or/folder --model_path path/to/model --config_path path/to/config
```
If you want to export prediction pickles and cropped predictions add `--pickle` and `--crop` arguments. If you want to change crop extension type, set it as `--visual_export_format JPG`.
If you want to perform standard prediction instead of sliced …
=> update predict script arguments

docs/COCO.md, sahi/utils/coco.py, tests/test_cocoutils.py
`coco.stats` will return dataset stats:
```python
{
'avg_annotation_area': 2448.405738278109,
'avg_num_annotations_in_image': 53.037243084530985,
'max_annotation_area': 328640,
'max_num_annotations_in_image': 902,
'min_annotation_area': 3,
'min_num_annotations_in_image': 1,
'num_annotations': 343204,
'num_annotations_per_category': {
'human': 106396,
'vehicle': 236808
},
'num_categories': 2,
'num_images': 6471,
'num_images_per_category': {
'human': 5684,
'vehicle': 6323
}
}
```
=> add stats property for Coco class

docs/COCO.md, sahi/utils/coco.py, tests/test_cocoutils.py
```python
from sahi.utils.coco import Coco
from sahi.utils.file import save_json
coco = Coco.from_coco_dict_or_path("coco.json")
area_filtered_coco = coco.get_area_filtered_coco(min=50)
area_filtered_coco = coco.get_area_filtered_coco(min=50, max=10000)
save_json(area_filtered_coco.json, "area_filtered_coco.json")
```
=> add get_area_filtered_coco method to Coco class

docs/COCO.md, sahi/utils/coco.py
fixes #81 
```python
from sahi.utils.coco import Coco
coco = Coco.from_coco_dict_or_path("coco.json")
coco.stats
{
'num_images': 6471,
'num_annotations': 343204,
'num_categories': 2,
'num_negative_images': 0,
'num_images_per_category': {'human': 5684, 'vehicle': 6323},
'num_annotations_per_category': {'human': 106396, 'vehicle': 236808},
'min_num_annotations_in_image': 1,
'max_num_annotations_in_image': 902,
'avg_num_annotations_in_image': 53.037243084530985,
'min_annotation_area': 3,
'max_annotation_area': 328640,
'avg_annotation_area': 2448.405738278109,
'min_annotation_area_per_category': {'human': 3, 'vehicle': 3},
'max_annotation_area_per_category': {'human': 72670, 'vehicle': 328640},
}
```
=> improve .stats

docs/COCO.md, sahi/utils/coco.py, tests/test_cocoutils.py
```python
from sahi.utils.coco import Coco
coco = Coco.from_coco_dict_or_path("coco.json", ignore_negative_samples=True)
```
=> utilize ignore_negative_samples property

sahi/annotation.py, sahi/model.py, sahi/postprocess/combine.py, sahi/postprocess/legacy/merge.py, sahi/predict.py, sahi/prediction.py, sahi/slicing.py, sahi/utils/coco.py, sahi/utils/cv.py, scripts/slice_coco.py, tests/data/models/mmdet_cascade_mask_rcnn/coco_instance.py, tests/data/models/mmdet_retinanet/coco_detection.py, tests/test_predict.py, tests/test_slicing.py
- export visuals with predicted + gt annotations into `visuals_with_gt` folder when `coco_file_path` is provided
- keep source folder structure when exporting results
- add `from_coco_annotation_dict` classmethod to `ObjectAnnotation`
- remove unused imports/classes/parameters
- better typing hints
=> minor refactorization, export visuals with gt

docs/SCRIPTS.md, scripts/coco_error_analysis.py, scripts/coco_evaluation.py
```bash
python scripts/coco_evaluation.py dataset.json results.json
```
will calculate coco evaluation and export them to given output folder directory.
If you want to specify mAP metric type, set it as `--metric bbox mask`.
If you want to also calculate classwise scores add `--classwise` argument.
If you want to specify max detections, set it as `--proposal_nums 10 100 500`.
If you want to specify a psecific IOU threshold, set it as `--iou_thrs 0.5`. Default includes `0.50:0.95` and `0.5` scores.
If you want to specify export directory, set it as `--out_dir output/folder/directory `.
```bash
python scripts/coco_error_analysis.py dataset.json results.json
```
will calculate coco error plots and export them to given output folder directory.
If you want to specify mAP result type, set it as …
=> add `coco_evaluation` script, refactor `coco_error_analysis` script

demo/inference_for_mmdetection.ipynb, demo/inference_for_yolov5.ipynb, sahi/model.py, sahi/predict.py, scripts/predict.py, scripts/predict_fiftyone.py, tests/test_mmdetectionmodel.py, tests/test_predict.py, tests/test_yolov5model.py
in `predict` and `predict_fiftyone` funtions:
- replaced `model_name` arg with `model_type`
- replaced `model_parameters` arg with `model_path, model_config_path, model_confidence_threshold, model_device, model_category_mapping, model_category_remapping`
in DetectionModel base class:
- replaced `prediction_score_threshold` arg with `confidence_threshold`
updated demo notebooks accordingly
=> refactor predict api

sahi/utils/mot.py
[https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/mot2coco.py](url)  script throws AssertionError because there is no field indicating video name on seqinfo.ini files produced by the current _create_info_file method in the mot class.
=> add additional fields to seqinfo.ini for mot utils

MANIFEST.in, requirements.txt, setup.py
The `requirements.txt` file was not included in [sahi-0.8.0.tar.gz](https://files.pythonhosted.org/packages/8a/bb/b112407386621507892dcbd51d97cb4be1192fb0530a9da4988b40f604fe/sahi-0.8.0.tar.gz) on PyPI, which is causing the conda packaging to fail at https://github.com/conda-forge/staged-recipes/pull/16106/files#r703927160.
<details>
```python-traceback
Processing $SRC_DIR
Created temporary directory: /tmp/pip-req-build-3127h4fo
DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
pip 21.3 will remove support for this functionality. You can find discussion regarding this at …
```
=> Include requirements.txt in sdist

sahi/model.py, sahi/predict.py, sahi/scripts/coco2yolov5.py, sahi/scripts/coco_error_analysis.py, sahi/scripts/coco_evaluation.py, sahi/scripts/slice_coco.py
export directories are printed after process finishes for:
- predict
- coco error analysis
- coco evaluation
- slice coco
- coco to yolov5 converter
remove redundant logger lines in `model.py`
add `min_area_ratio` param to `sahi coco slice` cli.
=> print exports dirs after process finishes

sahi/predict.py
with lower confidence threshold values, NMS gives better results
with higher confidence threshold values, NMM gives better results
after this pr, default postprocess type is `GREEDYNMM` when `model_confidence_threshold>=0.1`, `NMS` when `model_confidence_threshold<0.1` for `predict` cli and function.
=> add auto postprocess type to predict

sahi/scripts/coco2fiftyone.py, sahi/utils/fiftyone.py
- utilize `add_coco_labels()` from fiftyone
- handle when coco image ids are not sequential
- handle fiftyone bug: https://github.com/voxel51/fiftyone/issues/845
=> refactor fiftyone utils

sahi/predict.py
If the model returns only one prediction, the NMS postprocessing fails with the following error.
```
Traceback (most recent call last):
File "/home/tureckova/Code/TACR_TREND/sahi/sahi_predict-folder.py", line 29, in <module>
predict(
File "/home/tureckova/.local/lib/python3.8/site-packages/sahi/predict.py", line 477, in predict
prediction_result = get_sliced_prediction(
File "/home/tureckova/.local/lib/python3.8/site-packages/sahi/predict.py", line 290, in get_sliced_prediction
object_prediction_list = postprocess(object_prediction_list)
File "/home/tureckova/.local/lib/python3.8/site-packages/sahi/postprocess/combine.py", line 480, in __call__
keep = batched_nms(
File "/home/tureckova/.local/lib/python3.8/site-packages/sahi/postprocess/combine.py", line 34, in batched_nms …
```
=> fix NMS bug

README.md, docs/cli.md, sahi/predict.py, sahi/utils/cv.py, tests/test_predict.py
This PR brings full support for sliced/standard inference for video input format for all MMDetection/Detectron2/YOLOv5 models :fire: 
- Just give video file as source:
```bash
sahi predict --model_path yolov5s.pt --model_type yolov5 --source video.mp4 --export_visual
``` 
You can also view video render during video inference with `--view_video`:
```bash
sahi predict --model_path yolov5s.pt --model_type yolov5 --source video.mp4 --export_visual --view_video
``` 
- To `forward 100 frames`, on opened window press key `D `
- To `revert 100 frames`, on opened window press key `A`
- To `forward 20 frames`, on opened window press key `G`
- To `revert 20 frames`, on opened window press key `F`
- To `exit`, on opened window press key `Esc`
Note: If `--view_video` is slow, you can add …
=> add support for video prediction

sahi/auto_model.py, sahi/predict.py, sahi/utils/file.py, tests/test_predict.py
New `AutoDetectionModel` class makes it easier to load any `yolov5`,  `mmdet`, `detectron2` model!
```python
from sahi import AutoDetectionModel
detection_model = AutoDetectionModel.from_local(
model_type='yolov5',
model_path='yolov5s.pt',
image_size=640,
)
detection_model = AutoDetectionModel.from_local(
model_type='mmdet',
model_path='model.pt',
model_config='config.py',
image_size=640,
)
detection_model = AutoDetectionModel.from_local(
model_type='detectron2',
model_path='model.pt',
model_config='config.yaml',
image_size=640,
)
```
=> add automodel structure for unified model loading

docs/coco.md, sahi/utils/coco.py, tests/test_cocoutils.py
* COCO prediction object of class `CocoPrediction` can be added into COCO image object of class `sahi.utils.cocoCocoImage` using method `<CocoImage_Instance>.add_prediction`
* `__repr__` method updated to reflect predictions in class `sahi.utils..coco.CocoImage`
* Additional property `prediction_array` added in class `sahi.utils.coco.Coco` to export COCO predictions in json-serializable format. Logic for the property is defined in new function `sahi.utils.coco.create_coco_prediction_array` 
* added the test cases for the same in `test_cocoutils.py`
* updated file `coco.md` with necessary documentation
```python
from sahi.utils.coco import Coco, CocoImage, CocoAnnotation, CocoPrediction
from sahi.utils.file import save_json
coco_obj = Coco()
for _ in range(n):
image = CocoImage(**kwargs) …
```
=> Added support for exporting predictions in COCO format

docs/cli.md, requirements.txt, sahi/cli.py, sahi/utils/fiftyone.py, sahi/utils/import_utils.py, sahi/utils/mot.py, sahi/utils/torch.py, sahi/utils/torchvision.py, tests/test_detectron2.py
Print related package versions in the current env as:
```bash
>> sahi env
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   torch version 1.11.0 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   torchvision version 0.12.0 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   yolov5 version 6.1.3 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   mmdet version 2.25.0 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   mmcv version 1.5.3 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   detectron2 version 0.6+cpu is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   transformers version 4.20.0 is available.
06/19/2022 21:24:52 - INFO - sahi.utils.import_utils -   timm …
```
=> improve requirements and import handling

sahi/model.py
=> pybboxes allow oob, strict=False fix.

sahi/postprocess/combine.py, tests/test_huggingfacemodel.py, tests/test_predict.py, tests/test_torchvision.py
If there is only one box, there is a object that cannot be displayed in the box because it does not enter keep_to_merge_list.
=> Fixed a bug in greedynmm func

demo/inference_for_detectron2.ipynb, demo/inference_for_huggingface.ipynb, demo/inference_for_mmdetection.ipynb, demo/inference_for_torchvision.ipynb, demo/inference_for_yolov5.ipynb, sahi/__init__.py, sahi/models/base.py, sahi/models/detectron2.py, sahi/models/huggingface.py, sahi/models/mmdet.py, sahi/models/torchvision.py, sahi/models/yolov5.py, sahi/postprocess/combine.py, sahi/postprocess/utils.py, sahi/predict.py, sahi/prediction.py, sahi/utils/cv.py, sahi/utils/torch.py, tests/test_detectron2.py, tests/test_huggingfacemodel.py, tests/test_mmdetectionmodel.py, tests/test_predict.py, tests/test_torchvision.py, tests/test_yolov5model.py
- add batch support to all models (hf, torchvision, mmdet, yolov5)
- add batch inference for `get_sliced_inference` and `get_inference` functions
- use torchvision batched_nms when possible
- set default postprocess type and metric to NMS and IOU
- rename object_prediction_list to object_predictions
=> add batch inference support, rename object_prediction_list

sahi/utils/coco.py, sahi/utils/file.py
@fcakyon 
Eğitim yaparken indent "None" olması gerekiyor. Int değeri verildiğinde json dosyasını okuyamıyor.  SAHI ile coco işlemleri yapan kullanıcılar hata almaması için default değerin None olması daha doğru olacaktır.
Colab da yolov5 coco desteğini kullanabilmek için shutil.copy ekledim. Merge edildikten sonra paket sürümünü güncelleyebilir misiniz?
=> fix json.decoder.JSONDecodeError in coco to yolov5 conversion

sahi/utils/coco.py
It throws a warning when segmentation is None.
=> Fix RLE when segmentation is None

sahi/models/yolov8.py
- Allow user to pass custom yolo config through the standard yolo yaml config file
- Pass the confidence threshold to inner model to avoid prefiltering with default yolo threshold=0.25
For yolov8, the predict configuration is given at inference time.
We can pass full parameters using the "cfg" argument and a yaml configuration file.
Passing the "conf" argument using confidence_threshold also avoids to prefilter boxes in the underlying yolo model.
=> Improve yolov8 config

sahi/models/mmdet.py, sahi/predict.py, sahi/utils/cv.py
I was using "predict" cli tool for video inference and realized this issue after weird inference results. When I checked the implementation I noticed the colro space conversion from BGR2RGB is not done for video inputs, while it is done for image inputs. As a result it provides 2 different results 
* when you chop a video to frames and give the folder path of images as input
* when you give the video path as input
Here is my command:
`sahi predict --slice_width 1080 --slice_height 1080 --overlap_height_ratio 0.2 --overlap_width_ratio 0.2 --model_confidence_threshold 0.25 --model_path "<my-yolo-model>.pt" --model_type yolov5 --source "20240315_145057000_iOS.mp4" --export_crop`
1. When you provide the an image directory or image path to the tool, sahi reads images with cv2 and does color …
=> fix for using bgr image in inference instead of rgb

requirements.txt
PyPI version of `opencv-python` package is 4.9.0.80.
Previous relaxation of opencv-python version (#1035) is not allowing SAHI to be used alongside `albumentations` package, that has a `MIN_OPENCV_VERSION = "4.9.0.80"` ([setup.py](https://github.com/albumentations-team/albumentations/blob/main/setup.py)).
So I propose to use this version in pip requirements to be able to actually utilize a pre-built opencv-python package.
=> Use PyPI 4.9 opencv-python version in requirements

requirements.txt
Changes in https://github.com/obss/sahi/pull/1047 means that `import sahi` won't work with `shapely=1.8` installed due to this line:
https://github.com/obss/sahi/blob/de405626dcd9b98e8148435476727a6045d74ff9/sahi/utils/coco.py#L17
Full error (copied from https://github.com/conda-forge/sahi-feedstock/pull/60#issuecomment-2495819447:
```python-traceback
import: 'sahi'
Traceback (most recent call last):
File "/home/conda/feedstock_root/build_artifacts/sahi_1732418500825/test_tmp/run_test.py", line 2, in <module>
import sahi
File "/home/conda/feedstock_root/build_artifacts/sahi_1732418500825/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/python3.7 …
```
=> Pin shapely>2.0.0

requirements.txt
Given sahi recently relaxed the upper pin on OpenCV to 4.10 at https://github.com/obss/sahi/pull/1106, we can probably revert https://github.com/obss/sahi/pull/1057 to support Numpy 2.0.
References:
- https://github.com/opencv/opencv/wiki/OpenCV-Change-Logs-v2.2%E2%80%90v4.10#version4100
- https://github.com/conda-forge/opencv-feedstock/pull/417
- https://github.com/conda-forge/sahi-feedstock/pull/58#discussion_r1674691543
=> Remove numpy<2 upper pin

README.md, pyproject.toml, sahi/auto_model.py, sahi/models/torchvision.py, sahi/models/ultralytics.py, sahi/predict.py, sahi/utils/cv.py, tests/test_ultralyticsmodel.py
=> Fix OBB prediction and update Ultralytics demo notebook 

.github/workflows/ci.yml, README.md, pyproject.toml, sahi/models/mmdet.py, tests/test_mmdetectionmodel.py
- Upgrade PyTorch to version 2.3.1
- Update torchvision to version 0.18.1
- Add Python 3.12 support in classifiers
- Update mmengine, mmcv, and mmdet to latest versions
- Remove version-specific dependencies
=> Improve suppot for latest mmdet (v3.3.0)

pyproject.toml
Bump package versions:
- yolov5 from >=7.0.13 to >=7.0.14
- ultralytics from >=8.3.50 to >=8.3.86
=> Improve support for latest yolov5-pip and ultralytics versions

README.md, docs/README.md, docs/cli.md, docs/coco.md, docs/predict.md, docs/slicing.md, sahi/cli.py, sahi/models/huggingface.py, sahi/scripts/coco2yolo.py, sahi/utils/coco.py, tests/test_cocoutils.py
- Rename `coco yolov5` command to `coco yolo`
- Update CLI, documentation, and utility functions to support Ultralytics YOLO models
- Deprecate YOLOv5-specific methods in favor of more generic YOLO support
- Update README, CLI, and documentation references to reflect new naming
- Improve compatibility with latest Ultralytics versions
=> refctor coco to yolo conversion, update docs

sahi/utils/cv.py
Add the short-hand TIFF file extension to the `IMAGE_EXTENSIONS_LOSSLESS` list.
=> Fix: Predict cannot find TIF files in source directory

.github/workflows/ci.yml
Apparently, the version specifier needs to be in quotes.
=> fix ci workflow bug

sahi/models/roboflow.py
Hello @fcakyon, today I discovered a minor bug in my recent contribution. While testing with a small interactive Gradio app I built for sharing (comming days), I noticed a slight discrepancy between the inference and rfdetr packages regarding the parameter set of the predict method.
* [`sahi/models/roboflow.py`](diffhunk://#diff-74f3a01464f072466c6e7fd5cb49ef747e31488601730d920bb44967b8f72d2cL150-R150): Changed the parameter from `confidence` to `threshold` in the `predict` method call to ensure compatibility with the model's interface.
Apologies for the small PRs ... just trying to keep things tidy. 🙏
=> fix: Update inference method to use 'threshold' instead of 'confidence'

sahi/prediction.py, tests/test_predict.py
The overloaded operators allow, to use the prediction score class like:
```py
prediction_score = PredictionScore(0.6)
assert prediction_score == 0.6
assert prediction_score > 0.5
assert prediction_score < 0.7
```
=> Add overloaded operators for prediction score

sahi/annotation.py
Using mutable arguments, especially supplying mutable default arguments, is dangerous. 
Consider the following example:
```py
class A:
def __init__(self, c=[0, 0]):
self.c = c
a = A()
b = A()
a.c[0] = 99
print(b.c) 
print(A().c)
```
Will output:
[99, 0]
[99, 0]
I.e. changing the mutable default list of a class instance will change the default value for all subsequently created instances.
=> Use immutable arguments for bounding boxes

README.md
<div>
<a href="https://context7.com/obss/sahi"><img src="https://img.shields.io/badge/Context7%20MCP-Indexed-blue" alt="Context7 MCP"></a>
<a href="https://context7.com/obss/sahi/llms.txt"><img src="https://img.shields.io/badge/llms.txt-✓-brightgreen" alt="llms.txt"></a>
</div>
SAHI's documentation is [indexed in Context7 MCP](https://context7.com/obss/sahi), providing AI coding assistants with up-to-date, version-specific code examples and API references. We also provide an [llms.txt](https://context7.com/obss/sahi/llms.txt) file following the emerging standard for AI-readable documentation. To integrate SAHI docs with your AI development workflow, check out the [Context7 MCP installation guide](https://github.com/upstash/context7#%EF%B8%8F-installation).
=> Add Context7 MCP badges and documentation integration details

sahi/predict.py
This PR improves the profiling output of the `get_sliced_prediction` function.
- Currently the `get_prediction` returns a durations_in_seconds dictionary with the keys "prediction" and "postprocess" but get_sliced_prediction doesn't return the "postprocess" key and it's value. So this PR adds explicit timing of the postprocessing step, matching the output of `get_prediction`.
- **Bugfix:** Fixes overlapping duration measurements. Previously, the `"prediction"` timer included both the slicing and postprocessing durations, leading to inflated and misleading timing stats.
Now, each key in the `durations_in_seconds` output is mutually exclusive:
- `"slice"`: Time spent slicing the image
- `"prediction"`: Time spent running the model inference on slices (excluding slicing and postprocessing)
- …
=> Add postprocess duration and fix overlapping timers in get_sliced_prediction 

context7.json
**Overview**: Optimizes Context7 configuration by streamlining file exclusion rules and adding valuable documentation guidance, improving AI code analysis coverage while reducing configuration complexity.
- **Configuration: Simplify exclusion rules** - Removes 17 redundant file/folder exclusions that were overly broad in `context7.json:L16-L40`
- Verification: ✓ File exists, ✓ Line numbers accurate, ✓ Removes build artifacts and system files
- Trade-off: Less restrictive exclusions for better code analysis coverage
- **Documentation: Add CHANGELOG.md inclusion** - Includes changelog file for better project history context in `context7.json:L8`
- Impact: Context7 can now analyze project evolution and version changes
- Verification: ✓ Addition confirmed, ✓ Follows existing folder pattern
- …
=> docs: Simplify and improve context7 config

.github/workflows/ci.yml
**Overview**: Optimizes CI workflow efficiency by preventing unnecessary builds when documentation and configuration files are updated, reducing resource consumption and developer wait times.
- **Infrastructure: Add CI path exclusions** - Prevents CI triggers for documentation/config files in `.github/workflows/ci.yml:L11-12` and `L22-23`
- Files excluded: `context7.json` (documentation metadata) and `mkdocs.yml` (documentation build config)
- Verification: ✓ Applied to both push and pull_request triggers, ✓ Follows existing exclusion pattern
- **Consistency: Mirror exclusion across triggers** - Ensures both push and PR workflows skip builds for the same non-functional files
- Pattern alignment: Matches existing exclusions for `docs/**`, `demo/**`, and `**.cff` files
- Verification: ✓ …
=> build: Eliminate unnecessary CI workflow triggers
